/* ============================================================
   JING herb-data.js — Full clinical dossiers for all 55 herbs
   ============================================================ */
window.HERB_DATA = {

reishi:{
  eyebrow:'Fungal adaptogen · Basidiomycota',grade:'B+',gradeSub:'Moderate–strong',evScore:72,
  quickStats:[{l:'Evidence grade',v:'B+',s:'Moderate–strong'},{l:'Studies',v:'47',s:'12 RCTs · 8 meta-analyses'},{l:'Typical dose',v:'1.5–9g',s:'Dual extract daily'},{l:'Safety',v:'Good',s:'Monitor anticoagulants'}],
  summary:['Reishi (Ganoderma lucidum) fruiting body and mycelium contain beta-1,3/1,6-glucan polysaccharides and over 100 lanostane-type triterpenes (ganoderic acids). Clinical evidence supports immune modulation and fatigue reduction. NK cell activity increases 20–40% above baseline in multiple RCTs.','Primary pathways: macrophage activation via dectin-1, NF-κB inhibition via ganoderic acids, and mild platelet aggregation inhibition via adenosine. Best-evidenced TCM mushroom for immune and fatigue outcomes.'],
  compounds:[{name:'Beta-glucan polysaccharides',cls:'Polysaccharide · Primary immunomodulator',desc:'Beta-1,3 and beta-1,6-glucans bind dectin-1 and complement receptors on macrophages, triggering NK cell upregulation. Standardised extracts: ≥20% polysaccharides by AOAC 995.16 method.'},{name:'Ganoderic acids (A–Z)',cls:'Lanostane triterpene · Anti-inflammatory',desc:'Over 100 distinct ganoderic acids. Suppress NF-κB via IκB kinase inhibition and inhibit 5-LOX. Found predominantly in fruiting body, not mycelium. Standardised: ≥1% triterpenes.'},{name:'Adenosine',cls:'Purine nucleoside · Antiplatelet',desc:'Responsible for antiplatelet and mild vasodilatory effects. Clinically significant interaction with anticoagulants.'}],
  mechanisms:[{name:'Macrophage activation via dectin-1',desc:'Beta-glucans bind dectin-1 → phagocytosis upregulation, IL-12 and TNF-α secretion, downstream NK cell activation.'},{name:'NF-κB pathway inhibition',desc:'Ganoderic acids suppress IκB kinase → reduced COX-2, IL-1β, IL-6 expression.'},{name:'HPA axis modulation',desc:'Attenuates cortisol response to stressors. Preliminary human data suggests anxiolytic effect.'}],
  outcomes:[{dot:'s',name:'Immune function (NK cell activity)',effect:'↑ Significant',studies:'8 RCTs',body:'2021 meta-analysis (n=1,004): NK cytotoxic activity +20–40% above baseline. IL-2 also elevated. Effect at 3g/day over 8+ weeks.',pmid:'33746083 · 29760938'},{dot:'s',name:'Cancer-related fatigue',effect:'↑ Significant',studies:'4 RCTs',body:'Significant reductions on FACIT-F and MFI-20 at 1.5–3g/day over 8–12 weeks. SMD ~0.4, consistent across trials.',pmid:'22203880 · 26354460'},{dot:'m',name:'Liver enzyme normalisation',effect:'↑ Moderate',studies:'3 RCTs',body:'Hepatoprotective effect via ganoderic acid-mediated lipid peroxidation reduction. Small trials, not yet replicated at scale.',pmid:'24184615'},{dot:'x',name:'Blood glucose / insulin sensitivity',effect:'→ Mixed',studies:'3 RCTs',body:'Strong animal data but inconsistent human RCTs. Two trials showed no significant effect on fasting glucose in healthy adults.',pmid:'19515245'}],
  studies:[{author:'Tang et al. 2021',n:104,dur:'8 wk',dose:'3g/d polysaccharide',outcome:'Fatigue (FACIT-F)',eff:'pos',effLabel:'↑ Sig.',pmid:'33746083'},{author:'Gao et al. 2003',n:143,dur:'12 wk',dose:'5.4g/d extract',outcome:'NK cell activity',eff:'pos',effLabel:'↑ Sig.',pmid:'14569606'},{author:'Jin et al. 2012',n:68,dur:'12 wk',dose:'1.5g/d extract',outcome:'Fatigue + QoL',eff:'pos',effLabel:'↑ Sig.',pmid:'22203880'},{author:'Oka et al. 2010',n:47,dur:'8 wk',dose:'3g/d polysaccharide',outcome:'Fasting glucose',eff:'neu',effLabel:'→ NS',pmid:'19515245'}],
  dosage:[{l:'Dual extract (water + ethanol)',d:'1.5–3g',u:'per day · recommended form',n:'Split into 2 doses. Water extraction captures polysaccharides; ethanol captures triterpenes. Single-solvent extracts are incomplete.'},{l:'Dried fruiting body',d:'5–9g',u:'per day · traditional TCM range',n:'Variable polysaccharide content. Fruiting body only — mycelium-on-grain contains primarily starch, not beta-glucans.'}],
  timing:[{k:'Onset',v:'4–8 weeks for immune outcomes'},{k:'With food',v:'Improves tolerability; fat aids triterpene absorption'},{k:'Pre-surgery',v:'Discontinue 2 weeks prior — antiplatelet effect'}],
  forms:[{name:'Dual extract (water + alcohol)',cls:'Captures both polysaccharide and triterpene fractions',desc:'Only form that delivers both bioactive classes. Verify extraction method on COA. Look for: ≥20% polysaccharides AND ≥1% triterpenes declared.'},{name:'Fruiting body vs mycelium',cls:'Fruiting body strongly preferred',desc:'Mycelium-on-grain products are predominantly starch. Look for "fruiting body" explicitly on the label.'}],
  safety:[{cls:'g',l:'Well established safety profile',t:'No serious adverse events in RCTs up to 12 months. Considered safe for long-term use in healthy adults.'},{cls:'a',l:'Antiplatelet effect',t:'Adenosine-mediated. Clinically relevant if on warfarin, aspirin, or antihypertensives. Monitor INR. Discontinue 2 weeks before surgery.'},{cls:'a',l:'GI side effects',t:'Mild GI discomfort in ~5% of users at initiation. Typically resolves in 1 week.'},{cls:'r',l:'Organ transplant recipients',t:'Immune stimulation may theoretically increase allograft rejection risk. Avoid.'}],
  interactions:[{drug:'Warfarin / anticoagulants',sev:'m',sevL:'Moderate',mech:'Adenosine antiplatelet activity potentiates anticoagulation',note:'Monitor INR; may need dose reduction'},{drug:'Immunosuppressants',sev:'h',sevL:'High — Avoid',mech:'Immune stimulation may counter immunosuppressive therapy',note:'Avoid in transplant patients'}],
  contraindications:[{sev:'r',name:'Organ transplant recipients',desc:'Immune stimulation theoretically increases allograft rejection risk.'},{sev:'r',name:'Pregnancy and lactation',desc:'No human safety data.'},{sev:'a',name:'Scheduled surgery',desc:'Discontinue at least 2 weeks prior due to antiplatelet effects.'}],
  tcm:[{k:'Classification',v:'Shen tonic · Qi tonic'},{k:'Taste',v:'Sweet · Bitter'},{k:'Temperature',v:'Neutral (平)'},{k:'Organs',v:'Heart · Lung · Liver · Kidney'},{k:'Indications',v:'Qi deficiency · Insomnia · Cough · Fatigue'}],
  refs:['Gao Y et al. (2003). A randomised, placebo-controlled study of Ganoderma lucidum on immune function. J Med Food. PMID 14569606','Tang W et al. (2021). Ganoderma lucidum for cancer-related fatigue. J Ethnopharmacol. PMID 33746083','Jin X et al. (2016). Ganoderma lucidum (Cochrane review). PMID 27048732']
},

ginseng:{
  eyebrow:'Root adaptogen · Araliaceae',grade:'A−',gradeSub:'Strong',evScore:85,
  quickStats:[{l:'Evidence grade',v:'A−',s:'Strong'},{l:'Studies',v:'112',s:'38 RCTs · 14 meta-analyses'},{l:'Typical dose',v:'200–400mg',s:'G115 extract daily'},{l:'Safety',v:'Good',s:'Avoid with warfarin'}],
  summary:['Panax ginseng has the largest clinical evidence base of any TCM herb. Ginsenosides Rb1, Rg1, and Re modulate the HPA axis, enhance cholinergic signalling, and improve glucose metabolism. A 2024 meta-analysis (15 RCTs, n=671) confirmed significant memory improvement (SMD=0.19, p<0.05).','57-RCT systematic review found strong evidence for glucose metabolism, psychomotor function, and pulmonary disease. G115 extract (Pharmaton/Ginsana) is the most clinically validated preparation.'],
  compounds:[{name:'Ginsenosides Rb1, Rg1, Re, Rd',cls:'Triterpenoid saponin · Primary bioactives',desc:'Over 150 ginsenosides identified. Rb1 and Rg1 modulate GABA, acetylcholine, and dopamine receptors. Rg1 is neuroprotective. Standardised to ≥4% total ginsenosides for cognitive outcomes.'},{name:'Panaxans (polysaccharides)',cls:'Immunomodulatory polysaccharide',desc:'Acidic polysaccharides activate macrophages and NK cells via pathways separate from ginsenoside steroid mechanisms.'},{name:'Polyacetylenes (falcarinol)',cls:'Cytotoxic polyacetylene · Minor bioactive',desc:'Minor constituents with cytotoxic activity in cancer cell lines. Contribute to overall antioxidant capacity.'}],
  mechanisms:[{name:'HPA axis modulation',desc:'Ginsenosides Rb1 and Rg1 suppress CRH in the hypothalamus and ACTH in the pituitary, reducing cortisol output. Core adaptogenic mechanism.'},{name:'Cholinergic enhancement',desc:'Rg1 increases acetylcholine synthesis, inhibits acetylcholinesterase, and upregulates muscarinic receptor density — primary mechanism for cognitive enhancement.'},{name:'Nitric oxide modulation',desc:'Ginsenosides increase endothelial NO synthesis, improving cerebral and peripheral blood flow.'}],
  outcomes:[{dot:'s',name:'Cognitive function (memory, attention)',effect:'↑ Significant',studies:'15 RCTs',body:'2024 meta-analysis (n=671): significant memory improvement SMD=0.19. Stronger at high doses (SMD=0.33). Acute single-dose effects also documented.',pmid:'39474788'},{dot:'s',name:'Blood glucose / insulin sensitivity',effect:'↑ Significant',studies:'12 RCTs',body:'Systematic review of 57 RCTs: strong evidence for glucose metabolism. Reduces fasting glucose and HbA1c in T2DM patients.',pmid:'21704950'},{dot:'s',name:'Immune function',effect:'↑ Significant',studies:'8 RCTs',body:'Enhances NK cell activity, interferon production, and phagocytosis. Particularly studied with influenza vaccination.',pmid:'15070533'},{dot:'m',name:'Erectile dysfunction',effect:'↑ Moderate',studies:'6 RCTs',body:'Red ginseng shows consistent IIEF score improvement. Mechanism: ginsenoside-mediated NO synthase upregulation.',pmid:'28154803'},{dot:'x',name:'Physical performance',effect:'→ Mixed',studies:'7 RCTs',body:'4 of 7 trials showed no improvement in physical performance. Not recommended as a sports performance supplement.',pmid:'21704950'}],
  studies:[{author:'Zeng et al. 2024',n:671,dur:'Meta-analysis',dose:'Various',outcome:'Memory (SMD 0.19)',eff:'pos',effLabel:'↑ Sig.',pmid:'39474788'},{author:'Park et al. 2020',n:90,dur:'24 wk',dose:'3g/d powder',outcome:'MCI cognition',eff:'pos',effLabel:'↑ Sig.',pmid:'PMC6989239'},{author:'Cho et al. 2007',n:45,dur:'8 wk',dose:'2.7g/d red ginseng',outcome:'T2DM glucose',eff:'pos',effLabel:'↑ Sig.',pmid:'17010228'},{author:'Vogler et al. 1999',n:252,dur:'Various',dose:'Various',outcome:'Physical performance',eff:'neu',effLabel:'→ NS',pmid:'10411808'}],
  dosage:[{l:'G115 extract (≥4% ginsenosides)',d:'200–400mg',u:'per day · most RCT evidence',n:'G115 (Ginsana) is the most studied formulation. Morning dose preferred.'},{l:'Whole root powder',d:'3–9g',u:'per day · traditional range',n:'Much higher dose needed without standardisation. Variable potency between products.'}],
  timing:[{k:'Onset',v:'Acute cognitive: 2–3 hours. Sustained: 4–8 weeks'},{k:'Cycling',v:'8–12 weeks on, 4 weeks off traditionally recommended'},{k:'Avoid',v:'Stimulants in evening — may cause insomnia at high doses'}],
  forms:[{name:'Korean red ginseng (steamed)',cls:'Most studied form · Higher ginsenoside diversity',desc:'Steaming converts ginsenosides, increasing Rg3 and other minor ginsenosides with stronger antitumour and immunomodulatory effects.'},{name:'White ginseng (dried)',cls:'Traditional form · Lower bioavailability',desc:'Less bioavailable than red ginseng. Still effective at higher doses.'}],
  safety:[{cls:'g',l:'Well tolerated overall',t:'Safe profile confirmed across 29 RCTs. No serious adverse events in systematic reviews.'},{cls:'a',l:'Insomnia at high doses',t:'Most common side effect. Take in morning. Reduce dose if sleep is affected.'},{cls:'a',l:'Drug interactions',t:'May reduce warfarin efficacy (CYP2C9 induction). Additive hypoglycaemia risk with insulin. Avoid MAO inhibitors.'},{cls:'a',l:'Pregnancy',t:'Ginsenoside Rb1 was teratogenic in rodents at high doses. Avoid in first trimester.'}],
  interactions:[{drug:'Warfarin',sev:'m',sevL:'Moderate',mech:'May reduce warfarin efficacy via CYP2C9 induction',note:'Monitor INR'},{drug:'Insulin / oral hypoglycaemics',sev:'m',sevL:'Moderate',mech:'Additive glucose-lowering',note:'Monitor blood glucose'},{drug:'MAO inhibitors',sev:'h',sevL:'High',mech:'Potentiates MAO inhibitor effects — headache and tremor reported',note:'Avoid combination'}],
  contraindications:[{sev:'a',name:'First trimester pregnancy',desc:'Ginsenoside Rb1 teratogenic in animal models at high doses.'},{sev:'a',name:'Hormone-sensitive conditions',desc:'Weak oestrogenic activity documented. Caution in ER+ breast cancer.'}],
  tcm:[{k:'Classification',v:'Supreme Qi tonic · Yuan Qi'},{k:'Taste',v:'Sweet · Slightly bitter'},{k:'Temperature',v:'Slightly warm (微温)'},{k:'Organs',v:'Lung · Spleen · Heart · Kidney'},{k:'Indications',v:'Qi deficiency · Fatigue · Palpitations · Cognitive decline'}],
  refs:['Zeng M et al. (2024). Effects of Ginseng on Cognitive Function: Meta-Analysis. Phytother Res. PMID 39474788','Vogler BK et al. (1999). Efficacy of ginseng: systematic review of RCTs. Eur J Clin Pharmacol. PMID 10411808']
},

'lions-mane':{
  eyebrow:'Fungal nootropic · Hericiaceae',grade:'B+',gradeSub:'Moderate–strong',evScore:78,
  quickStats:[{l:'Evidence grade',v:'B+',s:'Moderate–strong'},{l:'Studies',v:'54',s:'14 RCTs · 6 meta-analyses'},{l:'Typical dose',v:'500mg–3g',s:'Dual extract daily'},{l:'Safety',v:'Excellent',s:'No significant interactions'}],
  summary:["Lion's Mane (Hericium erinaceus) is the only natural compound with strong RCT evidence for NGF (nerve growth factor) synthesis in human neural tissue. Hericenones (fruiting body) and erinacines (mycelium) both stimulate NGF production via different chemical pathways.","Four RCTs in mild cognitive impairment show statistically significant improvements. Effects reverse within 4 weeks of cessation — confirming active mechanism rather than placebo. 2025 meta-analysis confirms cognitive benefit."],
  compounds:[{name:'Hericenones (C–K)',cls:'Aromatic compounds · NGF stimulator · Fruiting body',desc:'Small molecular weight allows blood-brain barrier penetration. Stimulate NGF synthesis and secretion from neurons and astrocytes. Most active at 0.1–10 μM. Exclusively in fruiting body.'},{name:'Erinacines (A–K)',cls:'Cyathane diterpenes · NGF stimulator · Mycelium',desc:'Erinacines A, B, and C stimulate NGF production specifically in the hippocampus and locus coeruleus. Erinacine A also has anti-neuroinflammatory effects independent of NGF.'},{name:'Beta-glucans',cls:'Immunomodulatory polysaccharide',desc:'High beta-glucan content (>40% in quality extracts). Quality marker: ≥25% beta-glucans on COA.'}],
  mechanisms:[{name:'NGF synthesis stimulation',desc:'Hericenones and erinacines increase NGF and TrkA mRNA expression in hippocampal neurons and astrocytes, promoting neuronal survival, axonal growth, and synaptic plasticity.'},{name:'BDNF upregulation',desc:'Erinacines increase BDNF independently of NGF, supporting hippocampal neurogenesis. Relevant to antidepressant effects.'},{name:'Anti-neuroinflammation',desc:'Erinacine A inhibits microglial activation and reduces IL-6, TNF-α, iNOS in the brain.'}],
  outcomes:[{dot:'s',name:'Mild cognitive impairment',effect:'↑ Significant',studies:'4 RCTs',body:'Mori et al. 2009 (n=30): significant MMSE and ADAS-cog improvement at 16 weeks 3g/day. Effects reversed on cessation. Replicated in 3 subsequent RCTs.',pmid:'18844328 · 30844304'},{dot:'s',name:'Anxiety and depression',effect:'↑ Significant',studies:'3 RCTs',body:'Two RCTs in menopausal women, one in general adults: significant anxiety and depression reduction at 2g/day over 4 weeks. Mechanism: BDNF upregulation.',pmid:'30670498'},{dot:'m',name:'Sleep quality',effect:'↑ Moderate',studies:'2 RCTs',body:'Significant sleep quality score improvements at ~2g extract/day. Effect modest but statistically significant.',pmid:'31413233'}],
  studies:[{author:"Mori et al. 2009",n:30,dur:'16 wk',dose:'3g/d powder',outcome:'MMSE, ADAS-cog',eff:'pos',effLabel:'↑ Sig.',pmid:'18844328'},{author:'Saitsu et al. 2019',n:31,dur:'12 wk',dose:'3g/d extract',outcome:'MCI battery',eff:'pos',effLabel:'↑ Sig.',pmid:'30844304'},{author:'Vigna et al. 2019',n:77,dur:'8 wk',dose:'400mg/d extract',outcome:'Depression (HAMD)',eff:'pos',effLabel:'↑ Sig.',pmid:'30670498'}],
  dosage:[{l:'Dual extract (fruiting body + mycelium)',d:'500mg–1g',u:'per day · standardised',n:'Most RCTs use 2–3g/day fruiting body powder. 500mg extract ≈ 3g dried powder.'},{l:'Fruiting body powder',d:'2–3g',u:'per day · most common RCT dose',n:'Form used in Mori 2009. Must be taken continuously — effects reverse 4 weeks after stopping.'}],
  timing:[{k:'Onset',v:'4–8 weeks for measurable cognitive improvement'},{k:'Continuous use required',v:'Effects reverse within 4 weeks of stopping'},{k:'Best time',v:'Morning; divided doses improve tolerability'}],
  forms:[{name:'Dual extract (fruiting body + mycelium)',cls:'Both bioactive classes — recommended',desc:'Hericenones are in fruiting body; erinacines in mycelium. Best products contain both. Avoid mycelium-on-grain products — high starch content, low erinacine concentration.'},{name:'Standardisation',cls:'Look for: ≥1% hericenones or beta-glucan ≥25%',desc:'Many products do not declare standardisation. Request COA specifying beta-glucan content as minimum quality indicator.'}],
  safety:[{cls:'g',l:'Excellent safety profile',t:'No adverse events in any published RCT. Well tolerated up to 3g/day for 16 weeks. Among the safest supplements in the formulary.'},{cls:'a',l:'Rare allergic reactions',t:'Two case reports of allergic contact dermatitis. Start with low dose if mushroom allergy history.'},{cls:'g',l:'No drug interactions identified',t:'No clinically significant CYP450 interactions at therapeutic doses.'}],
  interactions:[{drug:'No established interactions',sev:'l',sevL:'None known',mech:'No significant CYP450 or platelet interactions',note:'Generally safe with all common medications'}],
  contraindications:[{sev:'a',name:'Known mushroom allergy',desc:'Cross-reactivity with other fungi possible.'},{sev:'a',name:'Pregnancy',desc:'No human safety data during pregnancy.'}],
  tcm:[{k:'Classification',v:'Qi tonic · Spleen and Stomach support'},{k:'Taste',v:'Sweet'},{k:'Temperature',v:'Neutral (平)'},{k:'Organs',v:'Spleen · Stomach · Heart · Kidney'},{k:'Indications',v:'Digestive weakness · Neurasthenia · Cognitive decline'}],
  refs:["Mori K et al. (2009). Improving effects of H. erinaceus on mild cognitive impairment. Phytother Res. PMID 18844328","Vigna L et al. (2019). Hericium erinaceus improves mood and sleep. Evid Based Complement Alternat Med. PMID 30670498"]
},

ashwagandha:{
  eyebrow:'Root adaptogen · Solanaceae',grade:'A−',gradeSub:'Strong',evScore:83,
  quickStats:[{l:'Evidence grade',v:'A−',s:'Strong'},{l:'Studies',v:'74',s:'28 RCTs · 10 meta-analyses'},{l:'Typical dose',v:'300–600mg',s:'KSM-66 extract daily'},{l:'Safety',v:'Good',s:'Avoid in hyperthyroidism'}],
  summary:['Ashwagandha (Withania somnifera) is the best-evidenced adaptogen in the formulary for cortisol reduction. KSM-66 and Sensoril are the two clinically validated extract forms. Withanolides are the principal bioactives.','2019 Chandrasekhar et al. (n=64): serum cortisol −27.9% vs placebo (p<0.001). Consistent across 8 independent RCTs. Also demonstrated: +14.7% testosterone in healthy men (Wankhede 2015), significant sleep quality improvement (Langade 2019).'],
  compounds:[{name:'Withanolides (withaferin A, withanolide D)',cls:'Steroidal lactone · Primary bioactive',desc:'Withaferin A inhibits NF-κB, HSP90, and proteasome. Withanolide D binds androgen receptors and suppresses SHBG. KSM-66 standardised to ≥5% withanolides.'},{name:'Alkaloids (withanine, somniferine)',cls:'Alkaloid · Anxiolytic',desc:'Contribute to anxiolytic and sleep-promoting effects via GABA-A receptor modulation.'},{name:'Sitoindosides VII–X',cls:'Glycowithanolide · Immunomodulatory',desc:'Enhance macrophage activity and support immune function.'}],
  mechanisms:[{name:'HPA axis downregulation',desc:'Withanolides reduce CRH in hypothalamus and ACTH in pituitary, resulting in measurably lower serum cortisol. Strongest evidence: 8 RCTs, consistent effect.'},{name:'Androgen receptor binding',desc:'Withanolide D binds androgen receptors with moderate affinity, reducing SHBG and increasing bioavailable testosterone. Plus LH upregulation.'},{name:'GABA-A receptor modulation',desc:'Alkaloid fraction binds GABA-A receptors at the benzodiazepine site, producing anxiolysis without sedation at standard doses.'}],
  outcomes:[{dot:'s',name:'Cortisol reduction / stress',effect:'↑ Significant',studies:'8 RCTs',body:'Chandrasekhar 2012 (n=64): cortisol −27.9% vs placebo (p<0.001). Most consistent cortisol-reduction evidence of any adaptogen.',pmid:'23439798 · 31297006'},{dot:'s',name:'Anxiety reduction',effect:'↑ Significant',studies:'7 RCTs',body:'Multiple meta-analyses confirm significant anxiety reduction on GAD-7, HAM-A, DASS. Effect size moderate-large (SMD ~0.7).',pmid:'32021735'},{dot:'s',name:'Testosterone (healthy men)',effect:'↑ Significant',studies:'4 RCTs',body:'Wankhede 2015: +14.7% testosterone vs placebo at 8 weeks. 2022 RCT: +15% at 16 weeks. SHBG reduction documented.',pmid:'30854916'},{dot:'s',name:'Sleep quality',effect:'↑ Significant',studies:'3 RCTs',body:'600mg KSM-66: significant improvement in PSQI sleep quality, efficiency, and latency.',pmid:'31728244'}],
  studies:[{author:'Chandrasekhar et al. 2012',n:64,dur:'60 days',dose:'300mg KSM-66',outcome:'Serum cortisol, PSS',eff:'pos',effLabel:'↑ Sig.',pmid:'23439798'},{author:'Lopresti et al. 2019',n:60,dur:'8 wk',dose:'240mg/d',outcome:'Cortisol, anxiety',eff:'pos',effLabel:'↑ Sig.',pmid:'31297006'},{author:'Wankhede et al. 2015',n:57,dur:'8 wk',dose:'300mg/d',outcome:'Testosterone, strength',eff:'pos',effLabel:'↑ Sig.',pmid:'26609282'},{author:'Langade et al. 2019',n:60,dur:'10 wk',dose:'300mg/d',outcome:'Sleep quality (PSQI)',eff:'pos',effLabel:'↑ Sig.',pmid:'31728244'}],
  dosage:[{l:'KSM-66 (≥5% withanolides)',d:'300–600mg',u:'per day · most RCT evidence',n:'300mg twice daily used in most RCTs. Evening dose aids sleep benefit.'},{l:'Sensoril (≥10% withanolides)',d:'125–250mg',u:'per day · more concentrated',n:'Lower dose needed. Particularly studied for anxiety.'}],
  timing:[{k:'Morning dose',v:'With breakfast — reduces GI side effects'},{k:'Evening dose',v:'Most useful for sleep benefit'},{k:'Onset',v:'Anxiety: 2–4 weeks. Testosterone: 6–8 weeks'}],
  forms:[{name:'KSM-66 (Ixoreal)',cls:'Best evidence base · Root-only extract',desc:'Most clinically validated form. ≥5% withanolides. Used in majority of published RCTs.'},{name:'Sensoril (Natreon)',cls:'Higher withanolide content',desc:'≥10% withanolides from root and leaf. Lower dose needed. Particularly used in anxiety trials.'}],
  safety:[{cls:'g',l:'Well tolerated',t:'Safe at 300–600mg/day for up to 12 weeks in trials.'},{cls:'a',l:'Thyroid interaction',t:'Increases T3 and T4. Avoid in hyperthyroidism. Monitor in hypothyroidism.'},{cls:'r',l:'Pregnancy',t:'Traditionally used as abortifacient at high doses. Avoid entirely during pregnancy.'}],
  interactions:[{drug:'Thyroid medications',sev:'m',sevL:'Moderate',mech:'Increases T3/T4 — additive with levothyroxine',note:'Monitor TSH'},{drug:'Sedatives / benzodiazepines',sev:'l',sevL:'Low',mech:'Additive GABA-A modulation',note:'May potentiate sedative effects'}],
  contraindications:[{sev:'r',name:'Pregnancy',desc:'Traditionally abortifacient at high doses. Avoid.'},{sev:'r',name:'Hyperthyroidism / Graves disease',desc:'Significantly increases T3/T4. May precipitate thyroid storm.'}],
  tcm:[{k:'Origin',v:'Ayurvedic medicine — adopted into TCM'},{k:'Temperature',v:'Warm'},{k:'Similar TCM class',v:'Kidney Yang and Jing tonics'},{k:'Indications',v:'Sexual vitality · Fatigue · Anxiety · Nervous exhaustion'}],
  refs:['Chandrasekhar K et al. (2012). KSM-66 Ashwagandha for stress. Indian J Psychol Med. PMID 23439798','Wankhede S et al. (2015). Ashwagandha and muscle recovery. J Int Soc Sports Nutr. PMID 26609282']
},

turmeric:{
  eyebrow:'Root · Zingiberaceae',grade:'A',gradeSub:'Strong',evScore:79,
  quickStats:[{l:'Evidence grade',v:'A',s:'Strong'},{l:'Studies',v:'96',s:'34 RCTs · 18 meta-analyses'},{l:'Typical dose',v:'500mg–1.5g',s:'Curcuminoids + piperine'},{l:'Safety',v:'Excellent',s:'Very low toxicity'}],
  summary:['Turmeric (Curcuma longa) curcuminoids — primarily curcumin (75%), demethoxycurcumin (20%), bisdemethoxycurcumin (5%) — have the broadest anti-inflammatory evidence base of any natural compound. Critical limitation: poor bioavailability. Piperine (BioPerine) increases absorption by ~2000%.','2018 meta-analysis (n=1,438): OA pain reduction comparable to NSAIDs. 2019 meta-analysis (n=531): significant antidepressant effect (SMD=0.34). NF-κB and COX-2 inhibition are the primary mechanisms.'],
  compounds:[{name:'Curcumin (75% of curcuminoids)',cls:'Polyphenol · Primary bioactive',desc:'Inhibits NF-κB, COX-2, LOX-5, and TNF-α. Rapidly metabolised — piperine, phytosomal, or liposomal formulation required for clinical equivalence to trial doses.'},{name:'Demethoxycurcumin & bisdemethoxycurcumin',cls:'Curcuminoid analogues · Minor bioactives',desc:'Contribute additional anti-inflammatory and antioxidant activity. Products standardised to "total curcuminoids" include all three.'},{name:'Ar-turmerone',cls:'Sesquiterpene · Neural stem cell support',desc:'Stimulates neural stem cell proliferation in vitro. Separate mechanism from curcumin.'}],
  mechanisms:[{name:'NF-κB inhibition',desc:'Curcumin directly inhibits IKKβ → reduced COX-2, iNOS, IL-1β, IL-6, TNF-α expression. Broadest single mechanism.'},{name:'NLRP3 inflammasome suppression',desc:'Inhibits NLRP3 inflammasome — key driver of chronic low-grade inflammation in metabolic syndrome and neurodegeneration.'},{name:'COX-2 and LOX-5 dual inhibition',desc:'Unlike NSAIDs, curcumin preferentially inhibits COX-2 and also inhibits 5-lipoxygenase. Comparable to celecoxib without cardiovascular risk.'}],
  outcomes:[{dot:'s',name:'Osteoarthritis pain and function',effect:'↑ Significant',studies:'11 RCTs',body:'2018 meta-analysis (n=1,438): significant pain reduction (SMD −1.07) and function improvement. Comparable to NSAIDs at 1–1.5g/day with piperine.',pmid:'29241860'},{dot:'s',name:'Depression symptoms',effect:'↑ Significant',studies:'9 RCTs',body:'2019 meta-analysis (n=531): significant antidepressant effect (SMD=0.34). Mechanism: BDNF upregulation, serotonin modulation, anti-neuroinflammation.',pmid:'31748590'},{dot:'s',name:'Inflammatory markers (CRP, IL-6)',effect:'↑ Significant',studies:'15 RCTs',body:'Consistent CRP, IL-6, and TNF-α reduction. Effect strongest in subjects with elevated baseline inflammation.',pmid:'25629927'},{dot:'m',name:'Non-alcoholic fatty liver disease',effect:'↑ Moderate',studies:'5 RCTs',body:'Significant improvements in liver enzymes, hepatic steatosis grade, and metabolic markers in NAFLD patients.',pmid:'26773065'}],
  studies:[{author:'Bannuru et al. 2018',n:1438,dur:'Meta-analysis',dose:'Various',outcome:'OA pain and function',eff:'pos',effLabel:'↑ Sig.',pmid:'29241860'},{author:'Ng et al. 2019',n:531,dur:'Meta-analysis',dose:'Various',outcome:'Depression (SMD 0.34)',eff:'pos',effLabel:'↑ Sig.',pmid:'31748590'},{author:'Sahebkar et al. 2015',n:507,dur:'Meta-analysis',dose:'Various',outcome:'CRP reduction',eff:'pos',effLabel:'↑ Sig.',pmid:'25629927'}],
  dosage:[{l:'Curcumin + piperine (BioPerine)',d:'500mg–1.5g',u:'curcuminoids daily · standard',n:'20mg piperine per 1g curcumin increases bioavailability ~20x. Most effective combination.'},{l:'Phytosomal curcumin (Meriva)',d:'200–400mg',u:'per day · enhanced bioavailability',n:'Phosphatidylcholine complex improves absorption. Lower dose needed.'}],
  timing:[{k:'With food',v:'Essential — fat-soluble compound. Take with fatty meal.'},{k:'With piperine',v:'Critical — take with black pepper extract or BioPerine'},{k:'Onset',v:'Anti-inflammatory: 1–2 weeks. Joint pain: 4–8 weeks'}],
  forms:[{name:'Curcumin 95% + piperine',cls:'Most cost-effective · Standard research form',desc:'Most RCTs use 95% curcuminoid extract with 5–20mg piperine. Ensure standardisation declared on label.'},{name:'Phytosomal (Meriva) or liposomal',cls:'Higher bioavailability · No piperine needed',desc:'Useful when GI tolerance of piperine is an issue. More expensive per dose.'}],
  safety:[{cls:'g',l:'Excellent safety profile',t:'Safe up to 8g/day in 3-month trials. GRAS status. No serious adverse events across hundreds of trials.'},{cls:'a',l:'GI side effects at high doses',t:'Nausea, diarrhoea at >3g/day. Divide doses and take with food.'},{cls:'a',l:'Gallstone caution',t:'Stimulates bile secretion. May exacerbate symptoms in gallstone disease.'}],
  interactions:[{drug:'Warfarin',sev:'m',sevL:'Moderate',mech:'Antiplatelet effect at high doses',note:'Monitor INR at doses >3g/day'},{drug:'Chemotherapy',sev:'m',sevL:'Moderate',mech:'In vitro evidence of both sensitisation and antagonism',note:'Consult oncologist before combining'}],
  contraindications:[{sev:'a',name:'Gallstones / bile duct obstruction',desc:'Curcumin stimulates bile secretion.'},{sev:'a',name:'Calcium oxalate kidney stones',desc:'Curcumin metabolised to oxalate. Avoid high doses.'}],
  tcm:[{k:'Classification',v:'Blood mover (活血化瘀) · Qi mover'},{k:'Taste',v:'Pungent · Bitter'},{k:'Temperature',v:'Warm'},{k:'Organs',v:'Spleen · Stomach · Liver · Lung'},{k:'Indications',v:'Blood stasis · Pain · Abdominal masses · Amenorrhoea'}],
  refs:['Bannuru RR et al. (2018). Comparative effectiveness of curcumin for osteoarthritis. Semin Arthritis Rheum. PMID 29241860','Ng QX et al. (2019). Clinical use of curcumin in depression. J Affect Disord. PMID 31748590']
},

ginkgo:{
  eyebrow:'Leaf extract · Ginkgoaceae',grade:'A−',gradeSub:'Strong',evScore:77,
  quickStats:[{l:'Evidence grade',v:'A−',s:'Strong'},{l:'Studies',v:'88',s:'30 RCTs · 15 meta-analyses'},{l:'Typical dose',v:'120–240mg',s:'EGb 761 extract daily'},{l:'Safety',v:'Moderate',s:'Antiplatelet — monitor'}],
  summary:['Ginkgo biloba is one of the most studied herbal medicines globally. EGb 761 (Dr. Willmar Schwabe GmbH) — standardised to 24% flavonoid glycosides and 6% terpene lactones — is the extract used in virtually all significant clinical trials.','Cochrane 2009 (36 trials): consistent benefit for dementia and cognitive impairment. Strong evidence for peripheral arterial disease (claudication) and tinnitus. Antiplatelet effect is clinically significant.'],
  compounds:[{name:'Ginkgoflavonoid glycosides (24%)',cls:'Flavonoid glycosides · Antioxidant · Vasodilatory',desc:'Quercetin, kaempferol, isorhamnetin glycosides. Inhibit platelet activating factor (PAF), improve endothelial function. The "24%" in EGb 761.'},{name:'Ginkgolides A, B, C + bilobalide (6%)',cls:'Diterpene lactone · PAF inhibitor · Neuroprotective',desc:'Ginkgolide B is the most potent natural PAF antagonist known. Bilobalide is neuroprotective via GABA receptor modulation and mitochondrial stabilisation.'},{name:'Ginkgolic acids',cls:'Removed in EGb 761 — allergenic if present',desc:'Raw ginkgo leaf contains ginkgolic acids which are allergenic. EGb 761 contains <5 ppm. Always use standardised extract.'}],
  mechanisms:[{name:'PAF inhibition',desc:'Ginkgolide B antagonises platelet activating factor → reduced platelet aggregation, improved microcirculation, reduced neuroinflammation.'},{name:'Cerebral blood flow enhancement',desc:'Flavonoid glycosides increase endothelial NO synthesis → vasodilation. Combined with PAF inhibition, significantly improves cerebral microcirculation.'},{name:'Mitochondrial stabilisation',desc:'Bilobalide protects mitochondrial membranes against ischaemic damage, upregulates Bcl-2, reduces cytochrome C release. Relevant in hypoperfusion states.'}],
  outcomes:[{dot:'s',name:'Dementia and cognitive impairment',effect:'↑ Significant',studies:'12 RCTs',body:'Cochrane 2012 (36 trials): consistent benefit at 240mg/day EGb 761. Modest effect size but clinically meaningful in moderate dementia.',pmid:'22786469'},{dot:'s',name:'Peripheral arterial disease',effect:'↑ Significant',studies:'8 RCTs',body:'Significant increase in pain-free walking distance. Effect equivalent to pentoxifylline in some comparisons.',pmid:'21171396'},{dot:'s',name:'Tinnitus',effect:'↑ Significant',studies:'5 RCTs',body:'2022 meta-analysis: significant reduction in tinnitus loudness and distress at 240mg/day. Best evidence for recent-onset tinnitus.',pmid:'35297286'},{dot:'m',name:'Altitude sickness prevention',effect:'↑ Moderate',studies:'3 RCTs',body:'Reduces incidence and severity of acute mountain sickness when started 24 hours before ascent.',pmid:'19616383'}],
  studies:[{author:'Birks et al. 2009 (Cochrane)',n:2372,dur:'Meta-analysis',dose:'120–240mg EGb 761',outcome:'Dementia outcomes',eff:'pos',effLabel:'↑ Sig.',pmid:'22786469'},{author:'Savage et al. 2022',n:714,dur:'Meta-analysis',dose:'240mg/d',outcome:'Tinnitus severity',eff:'pos',effLabel:'↑ Sig.',pmid:'35297286'},{author:'Tan et al. 2015',n:1628,dur:'22–24 months',dose:'240mg/d EGb 761',outcome:'Dementia prevention',eff:'pos',effLabel:'↑ Sig.',pmid:'25572879'}],
  dosage:[{l:'EGb 761 (24%/6% standardised)',d:'120–240mg',u:'per day in 2 divided doses',n:'120mg twice daily most common. 240mg/day for dementia prevention. Must be EGb 761 or equivalent.'},{l:'Other standardised extracts',d:'120–240mg',u:'per day',n:'Must be standardised to 24% flavonoid glycosides and 6% terpene lactones with ginkgolic acids removed.'}],
  timing:[{k:'Onset',v:'Claudication: 4–6 weeks. Cognitive: 8–12 weeks'},{k:'Divide doses',v:'Twice daily more effective than single dose'},{k:'Pre-surgery',v:'Discontinue 36 hours before any surgical procedure'}],
  forms:[{name:'EGb 761 (Dr. Willmar Schwabe)',cls:'Reference extract · All major trials used this form',desc:'Standardised to 24% flavonoid glycosides, 6% terpene lactones, <5 ppm ginkgolic acids. This is what the evidence is built on.'},{name:'Generic standardised extract',cls:'Must meet 24%/6% specification',desc:'Only equivalent if standardised to same ratios and tested for ginkgolic acid removal.'}],
  safety:[{cls:'a',l:'Antiplatelet — moderate risk',t:'Ginkgolide B inhibits PAF. Clinically significant antiplatelet effect. Monitor if on aspirin, NSAIDs, or anticoagulants.'},{cls:'g',l:'Well-tolerated long-term',t:'Good tolerability at standard doses for up to 2 years. No serious adverse events in major trials.'},{cls:'a',l:'Headache and GI effects',t:'Most common side effects. Reported in <5% of subjects.'}],
  interactions:[{drug:'Warfarin / anticoagulants',sev:'h',sevL:'High',mech:'PAF inhibition + anticoagulant = significant bleeding risk',note:'Avoid or monitor INR very closely'},{drug:'Aspirin / NSAIDs',sev:'m',sevL:'Moderate',mech:'Additive antiplatelet effect',note:'Monitor for bleeding at high doses'}],
  contraindications:[{sev:'h',name:'Concurrent anticoagulation',desc:'Significant bleeding risk with warfarin, heparin, or DOACs.'},{sev:'a',name:'Scheduled surgery',desc:'Discontinue 36 hours minimum before any surgical procedure.'},{sev:'a',name:'History of seizures',desc:'Ginkgo may lower seizure threshold.'}],
  tcm:[{k:'Classification',v:'Lung tonic · Kidney astringent'},{k:'Taste',v:'Sweet · Bitter · Astringent'},{k:'Temperature',v:'Neutral'},{k:'Organs',v:'Lung · Kidney'},{k:'Indications',v:'Cough · Asthma · Urinary frequency'}],
  refs:['Birks J, Grimley Evans J (2009). Ginkgo biloba for cognitive impairment. Cochrane Database. PMID 22786469','Savage JA et al. (2022). Meta-analysis of ginkgo for tinnitus. Laryngoscope Investig Otolaryngol. PMID 35297286']
},

'gotu-kola':{
  eyebrow:'Adaptogenic herb · Apiaceae',grade:'B−',gradeSub:'Moderate',evScore:54,
  quickStats:[{l:'Evidence grade',v:'B−',s:'Moderate'},{l:'Studies',v:'46',s:'13 RCTs · 3 meta-analyses'},{l:'Typical dose',v:'500mg–1g',s:'Standardised extract'},{l:'Safety',v:'Good',s:'Hepatic monitoring at >2g/day'}],
  summary:['Centella asiatica (Gotu Kola, 积雪草 / Ji Xue Cao) is a perennial wetland herb used in TCM, Ayurveda, and Thai medicine. Pentacyclic triterpenes — asiaticoside, madecassoside, asiatic acid, and madecassic acid — drive wound healing via collagen synthesis, and modulate cognition via BDNF and AChE pathways.','A 2017 systematic review and meta-analysis of 11 RCTs (Puttarak et al., Sci Rep) found significant improvements in alertness within 1 hour, but failed to find significant cognitive benefits across mixed outcomes — evidence is consistent for wound healing and venous insufficiency, more modest for cognition.'],
  compounds:[{name:'Asiaticoside & madecassoside',cls:'Pentacyclic triterpene saponins · Primary bioactives',desc:'Hydrolysed to asiatic acid and madecassic acid in vivo. Upregulate type I and III collagen synthesis, accelerate fibroblast proliferation, and inhibit matrix metalloproteinases. Standardised total triterpenes (TTFCA): ≥40%.'},{name:'Asiatic acid',cls:'Triterpenoid aglycone · BBB-permeable',desc:'Crosses blood-brain barrier. Studied for Alzheimer\'s and Parkinson\'s models — reduces beta-amyloid, protects hippocampal mitochondria from oxidative stress.'},{name:'Madecassic acid',cls:'Triterpenoid aglycone',desc:'Anti-inflammatory via NF-κB suppression. Improves venous tone in chronic venous insufficiency.'}],
  mechanisms:[{name:'Collagen synthesis upregulation',desc:'Asiaticoside increases collagen type I and III mRNA expression in fibroblasts. Mechanism behind accelerated wound re-epithelialisation in burn and diabetic ulcer RCTs.'},{name:'BDNF and acetylcholinesterase modulation',desc:'Asiatic acid increases BDNF expression in hippocampus and acts as a weak AChE inhibitor — proposed dual mechanism for cognitive and mood effects.'},{name:'Venous tone improvement',desc:'Triterpenes strengthen connective tissue around venous walls. EU clinical use for chronic venous insufficiency confirmed in Cochrane review.'}],
  outcomes:[{dot:'m',name:'Wound healing & scar appearance',effect:'↑ Significant',studies:'7 RCTs',body:'Consistent acceleration of wound closure, re-epithelialisation, and reduced scar size across burn, diabetic ulcer, and post-surgical RCTs. Topical and oral both effective. 2022 systematic review (MDPI) and 2024 review (Pharmaceutics) both positive.',pmid:'35330049 · 39499'},{dot:'m',name:'Alertness & mood',effect:'↑ Moderate',studies:'4 RCTs',body:'2017 Puttarak meta-analysis: statistically significant increase in alertness within 1 hour and reduction in anger scores. Effect on long-term cognition mixed.',pmid:'28878245'},{dot:'m',name:'Venous insufficiency',effect:'↑ Moderate',studies:'3 RCTs',body:'European clinical use established for chronic venous insufficiency. Reduces leg swelling and improves microcirculation.',pmid:'15378679'},{dot:'x',name:'Cognitive function (long-term)',effect:'→ Mixed',studies:'5 RCTs',body:'2017 meta-analysis found no significant cognitive benefit across pooled trials. Single 2016 stroke trial (Farhana, n=48) showed memory improvement vs folic acid at 1000mg.',pmid:'27123451'}],
  studies:[{author:'Farhana et al. 2016',n:48,dur:'6 wk',dose:'750–1000mg/d',outcome:'Post-stroke memory (MMSE)',eff:'pos',effLabel:'↑ Sig.',pmid:'27123451'},{author:'Wattanathorn et al. 2008',n:28,dur:'2 mo',dose:'750mg/d',outcome:'Cognitive function elderly',eff:'pos',effLabel:'↑ Sig.',pmid:'17604601'},{author:'Puttarak et al. 2017',n:'Meta-analysis',dur:'11 RCTs',dose:'Various',outcome:'Cognition + mood',eff:'neu',effLabel:'→ Mixed',pmid:'28878245'},{author:'Belcaro et al. 2011',n:87,dur:'8 wk',dose:'180mg TECA/d',outcome:'Venous insufficiency',eff:'pos',effLabel:'↑ Sig.',pmid:'21804474'}],
  dosage:[{l:'Standardised extract (TTFCA ≥40%)',d:'60–180mg',u:'per day · venous outcomes',n:'TECA / TTFCA standardised extract — used in most European RCTs for venous insufficiency.'},{l:'Whole-plant extract',d:'500mg–1g',u:'per day · cognitive outcomes',n:'Studies in cognition typically use 500–1000mg standardised extract. Effects on alertness within hours; long-term cognitive gains require 8+ weeks.'},{l:'Dried herb (TCM range)',d:'9–15g',u:'decoction · traditional',n:'Traditional decoction range. Less consistent than standardised extract.'}],
  timing:[{k:'Onset',v:'Alertness: within 1 hour. Cognition: 4–8 weeks. Wound healing: visible at 2–4 weeks.'},{k:'With food',v:'Improves tolerability; no major absorption impact.'},{k:'Cycling',v:'8 weeks on, 2 weeks off recommended at high oral doses to monitor liver enzymes.'}],
  forms:[{name:'TTFCA / TECA standardised extract',cls:'Most clinically validated form',desc:'Triterpene fraction of Centella asiatica. Used in most venous insufficiency and wound healing RCTs. Look for ≥40% total triterpenes.'},{name:'Topical 1% asiaticoside cream',cls:'Wound healing — established use',desc:'1% topical asiaticoside cream is the form used in burn wound RCTs and Asian post-operative care.'}],
  safety:[{cls:'g',l:'Generally well tolerated',t:'No serious adverse events reported in the 11-RCT 2017 meta-analysis. Mild GI upset in ~5% at high doses.'},{cls:'a',l:'Hepatotoxicity at high doses',t:'Rare case reports (Jorge & Jorge 2005) of liver injury at chronic high doses (>2g/day for months). Monitor ALT/AST if used long-term.'},{cls:'a',l:'Pregnancy',t:'Not enough human safety data. Traditional use as emmenagogue suggests caution — avoid in pregnancy.'},{cls:'a',l:'Sedation',t:'Mild sedative effect reported. May potentiate sedatives and CNS depressants.'}],
  interactions:[{drug:'Sedatives / benzodiazepines',sev:'m',sevL:'Moderate',mech:'Additive CNS depression',note:'Reduce dose if combining'},{drug:'Hepatotoxic drugs',sev:'m',sevL:'Moderate',mech:'Potential additive hepatic stress at high doses',note:'Monitor LFTs if used >8 weeks'},{drug:'Anti-diabetic medications',sev:'l',sevL:'Low',mech:'Mild hypoglycaemic effect reported',note:'Monitor blood glucose'}],
  contraindications:[{sev:'a',name:'Pregnancy and lactation',desc:'Traditional use as emmenagogue; insufficient human safety data.'},{sev:'a',name:'Active hepatic disease',desc:'Avoid at high doses; monitor enzymes if used at all.'},{sev:'a',name:'Scheduled surgery',desc:'Mild sedation may interact with anaesthesia — discontinue 1 week before.'}],
  tcm:[{k:'Classification',v:'Heat-clearing · Damp-resolving · Shen-calming'},{k:'Taste',v:'Bitter · Sweet'},{k:'Temperature',v:'Cool (凉)'},{k:'Organs',v:'Liver · Spleen · Kidney'},{k:'Indications',v:'Heat toxin · Damp-heat jaundice · Sores · Anxiety'}],
  refs:['Puttarak P et al. (2017). Effects of Centella asiatica on cognitive function and mood: systematic review and meta-analysis. Sci Rep 7:10646. PMID 28878245','Farhana KM et al. (2016). Centella asiatica vs folic acid in vascular cognitive impairment after stroke. Evid Based Complement Altern Med. PMID 27123451','Witkowska K et al. (2024). Topical Centella asiatica in wound healing. Pharmaceutics 16:1252','Belcaro G et al. (2011). Centella asiatica TECA in chronic venous insufficiency. Angiology. PMID 21804474']
},

'huang-lian':{
  eyebrow:'Berberine root · Ranunculaceae',grade:'A−',gradeSub:'Strong',evScore:78,
  quickStats:[{l:'Evidence grade',v:'A−',s:'Strong'},{l:'Studies',v:'84',s:'46 RCTs · 5 meta-analyses'},{l:'Typical dose',v:'500mg–1.5g',s:'Berberine HCl daily'},{l:'Safety',v:'Good',s:'Significant CYP interactions'}],
  summary:['Coptis chinensis (Huang Lian, 黄连) has the highest natural berberine content of any plant — between 51 and 96 mg/g of rhizome by HPLC (Shrivastava 2023). A 2022 systematic review of 46 RCTs (Liang et al.) showed berberine alone reduces HbA1c by an average of 0.73% — comparable to first-line metformin — while also improving FPG, 2hPG, HOMA-IR, BMI, and lipid profile.','A 2022 Frontiers meta-analysis of 33 RCTs (2,846 patients) confirmed Huang Lian decoction as a metformin adjunct: significant reductions in FBG (−1.16%), 2hPG (−1.64%), HbA1c (−0.78%), and HOMA-IR (−0.77%). One of the most evidence-rich single TCM herbs for metabolic syndrome.'],
  compounds:[{name:'Berberine',cls:'Isoquinoline alkaloid · Primary bioactive (51–96 mg/g)',desc:'Activates AMPK, the master metabolic switch. Upregulates GLUT4 translocation, inhibits hepatic gluconeogenesis, and modulates gut microbiota. Bioavailability <1% — efficacy is largely via gut and first-pass effects.'},{name:'Coptisine',cls:'Isoquinoline alkaloid · Secondary bioactive',desc:'Stronger antimicrobial activity than berberine. Also inhibits acetylcholinesterase and shows neuroprotective effects in pre-clinical models.'},{name:'Palmatine, jatrorrhizine, epiberberine',cls:'Protoberberine alkaloids',desc:'Synergistic with berberine on metabolic targets. Contribute to characteristic yellow colour and bitter taste.'},{name:'Polysaccharides',cls:'Antioxidant immunomodulator',desc:'Activates JNK pathway antioxidant response. Independent antidiabetic mechanism alongside alkaloids.'}],
  mechanisms:[{name:'AMPK activation',desc:'Berberine is a potent activator of AMP-activated protein kinase, mimicking the effect of metformin. Increases insulin sensitivity, glucose uptake, and fatty acid oxidation in muscle and liver.'},{name:'Hepatic gluconeogenesis suppression',desc:'Inhibits PEPCK and G6Pase expression in hepatocytes — reduces fasting plasma glucose by suppressing endogenous glucose production.'},{name:'Gut microbiota modulation',desc:'Increases Akkermansia muciniphila and other beneficial bacteria; reduces lipopolysaccharide-producing species. Improves intestinal barrier function and reduces systemic inflammation.'},{name:'LDL-receptor upregulation',desc:'Increases hepatic LDLR expression via a statin-independent pathway. Explains consistent LDL-cholesterol reductions in metabolic RCTs.'}],
  outcomes:[{dot:'s',name:'HbA1c reduction (T2DM)',effect:'↑ Significant',studies:'46 RCTs',body:'2022 meta-analysis (PubMed 34956436): berberine reduces HbA1c by 0.73% (95% CI −0.97 to −0.51), FPG by 0.86 mmol/L, 2hPG by 1.26 mmol/L. Comparable to metformin first-line therapy.',pmid:'34956436'},{dot:'s',name:'Lipid profile improvement',effect:'↑ Significant',studies:'24 RCTs',body:'Reduces TG (−0.50), TC (−0.64), LDL (−0.86 mmol/L) and increases HDL (+0.17 mmol/L). Statin-additive without rhabdomyolysis risk.',pmid:'34956436'},{dot:'s',name:'Insulin resistance (HOMA-IR)',effect:'↑ Significant',studies:'18 RCTs',body:'HOMA-IR reduction of 0.71 across pooled trials. BMI reduction of 1.07 kg/m² supports metabolic syndrome use.',pmid:'34956436'},{dot:'m',name:'PCOS metabolic markers',effect:'↑ Moderate',studies:'6 RCTs',body:'Improves insulin sensitivity and androgen profile in PCOS — comparable to metformin in two head-to-head trials.',pmid:'25104566'},{dot:'m',name:'Gut dysbiosis & SIBO',effect:'↑ Moderate',studies:'4 RCTs',body:'Strong antimicrobial action against pathogenic bacteria. Traditional use for dysentery now supported by RCT data in IBS-D and SIBO.',pmid:'31097948'}],
  studies:[{author:'Liang Y et al. 2022',n:'46 RCTs',dur:'Meta-analysis',dose:'0.5–1.5g/d',outcome:'HbA1c (−0.73%)',eff:'pos',effLabel:'↑ Sig.',pmid:'34956436'},{author:'Yin J et al. 2008',n:36,dur:'12 wk',dose:'1.5g/d berberine',outcome:'T2DM glucose',eff:'pos',effLabel:'↑ Sig.',pmid:'18397984'},{author:'Wei et al. 2022 (Frontiers)',n:'33 RCTs',dur:'Meta-analysis',dose:'HLP + metformin',outcome:'FBG, HbA1c, HOMA-IR',eff:'pos',effLabel:'↑ Sig.',pmid:'PMC9492976'},{author:'Wei W et al. 2012',n:89,dur:'3 mo',dose:'1.5g/d',outcome:'PCOS metabolic',eff:'pos',effLabel:'↑ Sig.',pmid:'22751844'}],
  dosage:[{l:'Berberine HCl',d:'500mg × 3',u:'per day · before meals',n:'1.5g/day in three divided doses is the standard RCT dose for T2DM. Take 20 minutes before each meal.'},{l:'Coptis chinensis rhizome (TCM)',d:'1.5–6g',u:'per day · decoction',n:'Traditional bitter decoction. Very bitter — usually combined with other herbs (e.g. Huang Lian Jie Du Tang).'},{l:'Standardised extract',d:'500mg–1g',u:'per day · ≥97% berberine',n:'Modern standardised extract. Same dose range as berberine HCl.'}],
  timing:[{k:'Onset',v:'Glucose lowering: visible at 2 weeks. HbA1c: 8–12 weeks.'},{k:'With food',v:'Take 20 minutes BEFORE meals for postprandial glucose effect.'},{k:'Cycling',v:'Not required — long-term use up to 2 years studied without tolerance.'},{k:'Avoid',v:'Concurrent grapefruit; CYP3A4 substrates without monitoring.'}],
  forms:[{name:'Berberine hydrochloride',cls:'Most-studied form · Highest purity',desc:'97%+ pure berberine HCl is the form used in nearly all metabolic RCTs. Yellow crystalline powder, intensely bitter.'},{name:'Berberine phytosome (Berberine-PCS)',cls:'Enhanced bioavailability form',desc:'Phospholipid-complexed berberine has 3–5× higher serum concentration. Promising but fewer RCTs.'},{name:'Whole rhizome decoction',cls:'Classical TCM form',desc:'Used in Huang Lian Jie Du Tang and Ban Xia Xie Xin Tang. Lower berberine dose but full alkaloid spectrum.'}],
  safety:[{cls:'g',l:'Well-tolerated metabolically',t:'Most common AEs are mild GI: diarrhoea, constipation, flatulence (~15% at full dose). Rare at <500mg/day.'},{cls:'r',l:'Pregnancy — contraindicated',t:'Crosses placenta and displaces bilirubin from albumin. Can cause kernicterus in neonates. AVOID in pregnancy and lactation.'},{cls:'r',l:'Neonates and infants',t:'Bilirubin displacement risk. Do not give to infants <3 months.'},{cls:'a',l:'Strong CYP inhibitor',t:'Inhibits CYP3A4, CYP2D6, and CYP2C9. Significant interactions with many prescription drugs — review all medications.'},{cls:'a',l:'P-glycoprotein inhibition',t:'Increases bioavailability of P-gp substrates including cyclosporine, digoxin.'}],
  interactions:[{drug:'Cyclosporine',sev:'h',sevL:'High',mech:'P-gp + CYP3A4 inhibition → 28–34% serum concentration increase',note:'Avoid combination or reduce cyclosporine dose 30%'},{drug:'Metformin',sev:'m',sevL:'Moderate · monitor',mech:'Additive AMPK activation and glucose lowering',note:'Beneficial but monitor for hypoglycaemia'},{drug:'Warfarin / DOACs',sev:'m',sevL:'Moderate',mech:'CYP2C9 inhibition may increase warfarin levels',note:'Monitor INR if combining'},{drug:'Statins',sev:'m',sevL:'Moderate · synergistic',mech:'Additive LDL-receptor upregulation',note:'Synergistic for LDL reduction; monitor liver enzymes'},{drug:'Macrolide antibiotics',sev:'m',sevL:'Moderate',mech:'CYP3A4 substrate competition',note:'Avoid concurrent erythromycin/clarithromycin'}],
  contraindications:[{sev:'r',name:'Pregnancy and lactation',desc:'Bilirubin displacement causes kernicterus risk in neonates.'},{sev:'r',name:'Infants under 3 months',desc:'Immature blood-brain barrier — neurotoxicity risk.'},{sev:'a',name:'Significant CYP3A4 substrates',desc:'Cyclosporine, tacrolimus, certain statins — review medication list.'},{sev:'a',name:'G6PD deficiency',desc:'Theoretical haemolysis risk based on related alkaloids.'}],
  tcm:[{k:'Classification',v:'Heat-clearing · Damp-resolving · Fire-purging'},{k:'Taste',v:'Very bitter (大苦)'},{k:'Temperature',v:'Cold (寒)'},{k:'Organs',v:'Heart · Liver · Stomach · Large Intestine'},{k:'Indications',v:'Damp-heat dysentery · Liver-fire · Heart-fire insomnia · Toxic heat sores'}],
  refs:['Liang Y et al. (2022). Effect of berberine on metabolic profiles in T2DM: meta-analysis of 46 RCTs. PMID 34956436','Wei X et al. (2022). Coptis chinensis as metformin adjunct in T2DM: 33-RCT meta-analysis. Front Pharmacol. PMC9492976','Yin J et al. (2008). Berberine vs metformin in T2DM. Metabolism. PMID 18397984','Wei W et al. (2012). Berberine in PCOS. Eur J Endocrinol. PMID 22751844','Shrivastava A et al. (2023). HPLC quantification of berberine in Coptis chinensis']
},

'rhodiola':{
  eyebrow:'High-altitude adaptogen · Crassulaceae',grade:'B',gradeSub:'Moderate',evScore:60,
  quickStats:[{l:'Evidence grade',v:'B',s:'Moderate'},{l:'Studies',v:'43',s:'11 RCTs · 2 meta-analyses'},{l:'Typical dose',v:'200–680mg',s:'Standardised extract'},{l:'Safety',v:'Excellent',s:'No major interactions'}],
  summary:['Rhodiola rosea (红景天 / Hong Jing Tian) is a perennial herb growing in high-altitude regions of Russia, Scandinavia, and the Tibetan Plateau. The two key bioactive groups are rosavins (unique to R. rosea) and salidroside (shared with other Rhodiola species) — typically standardised at 3:1 ratio.','The most-studied adaptogenic extract is SHR-5 (Swedish Herbal Institute), standardised to 3% rosavins and 1% salidroside. Best evidence for stress-related fatigue, burnout, and mental performance under load. 2024 endurance performance meta-analysis (Front Nutr) showed moderate benefits for time-to-exhaustion in trained subjects.'],
  compounds:[{name:'Rosavins (rosavin, rosin, rosarin)',cls:'Phenylpropanoid glycosides · Unique to R. rosea',desc:'Cinnamyl alcohol glycosides found only in Rhodiola rosea — used as the species authentication marker. Modulate monoamine neurotransmitters and HPA axis stress response. Standardised to 3%.'},{name:'Salidroside (rhodioloside)',cls:'Phenylethanoid glycoside · Common to Rhodiola species',desc:'Glucoside of tyrosol. Increases ATP and creatine phosphate in muscle, supports mitochondrial function, and has antioxidant activity. Standardised to 1%.'},{name:'Tyrosol',cls:'Phenolic compound · Aglycone of salidroside',desc:'Free tyrosol contributes to the antioxidant and dopaminergic profile. Also a constituent of olive oil.'}],
  mechanisms:[{name:'HPA axis modulation',desc:'Rosavins normalise cortisol response to stressors — neither pure suppression nor stimulation. The classic "adaptogenic" pattern: helps under-active systems and dampens over-active ones.'},{name:'Monoamine neurotransmitter modulation',desc:'Mild monoamine oxidase A inhibition + serotonin/dopamine precursor support. Mechanism for anti-fatigue and mood effects.'},{name:'Mitochondrial ATP support',desc:'Salidroside increases ATP and creatine phosphate availability in skeletal muscle, supporting endurance and recovery.'},{name:'Heat shock protein induction',desc:'Upregulates HSP70 — protects cells under physiological stress (heat, exercise, oxidative load).'}],
  outcomes:[{dot:'m',name:'Stress-related fatigue & burnout',effect:'↑ Significant',studies:'5 RCTs',body:'Most consistent indication. 576mg/day SHR-5 for 12 weeks: significant Maslach Burnout Inventory improvement (Olsson 2009, n=60). Pirelli study in physicians (n=56): significant fatigue reduction at 170mg/day.',pmid:'19500070'},{dot:'m',name:'Mental performance under load',effect:'↑ Moderate',studies:'3 RCTs',body:'Performance on cognitive tasks under sleep deprivation and stress: significant improvements with single doses of 200–400mg. Less effect in unstressed healthy adults.',pmid:'17990195'},{dot:'m',name:'Endurance & exercise capacity',effect:'↑ Moderate',studies:'6 RCTs',body:'2024 Frontiers meta-analysis: moderate improvement in time-to-exhaustion. Effects strongest in trained subjects. Caffeine combinations show synergy.',pmid:'40570064'},{dot:'x',name:'Depression (clinical)',effect:'→ Mixed',studies:'4 RCTs',body:'One 12-week trial (Mao 2015) vs sertraline showed smaller effect than SSRI but better tolerability. Not first-line; adjunct potential.',pmid:'25770981'}],
  studies:[{author:'Olsson EM et al. 2009',n:60,dur:'28 days',dose:'576mg/d SHR-5',outcome:'Burnout (Maslach BI)',eff:'pos',effLabel:'↑ Sig.',pmid:'19500070'},{author:'Darbinyan V et al. 2007',n:91,dur:'42 days',dose:'340mg/d SHR-5',outcome:'Depression (HAMD)',eff:'pos',effLabel:'↑ Sig.',pmid:'17990195'},{author:'Edwards D et al. 2012',n:101,dur:'8 wk',dose:'400mg/d WS 1375',outcome:'Stress symptoms',eff:'pos',effLabel:'↑ Sig.',pmid:'22228617'},{author:'Mao JJ et al. 2015',n:57,dur:'12 wk',dose:'340–680mg/d',outcome:'MDD vs sertraline',eff:'neu',effLabel:'→ Modest',pmid:'25770981'}],
  dosage:[{l:'SHR-5 standardised extract',d:'200–400mg',u:'per day · most clinical evidence',n:'3% rosavins, 1% salidroside. Morning or pre-task dose. 576mg/day used in burnout RCT.'},{l:'Higher-dose protocol',d:'400–680mg',u:'per day · depression / severe burnout',n:'Used in Mao 2015 and Darbinyan stress trials. Split into morning + early afternoon.'},{l:'Acute / single-dose',d:'288mg',u:'single dose · pre-task',n:'Pre-exam, pre-presentation, or pre-shift use. Effect within 30–60 minutes.'}],
  timing:[{k:'Onset',v:'Acute effect: 30–60 minutes. Sustained: 2–4 weeks.'},{k:'Time of day',v:'Morning only — afternoon doses can disrupt sleep at >300mg.'},{k:'With food',v:'Improves tolerability. No major absorption impact.'},{k:'Cycling',v:'No tolerance reported. 12-week continuous use shown safe in RCTs.'}],
  forms:[{name:'SHR-5 (rosavins 3% / salidroside 1%)',cls:'Most-studied — gold-standard form',desc:'Used in Olsson, Darbinyan, Edwards trials. The 3:1 rosavin:salidroside ratio mirrors the wild plant.'},{name:'WS 1375 / Rosalin',cls:'European pharmaceutical-grade extract',desc:'Standardised 5% rosavins, 1.8% salidroside. Used in Edwards 2012 generalised anxiety trial.'},{name:'Crude root powder',cls:'Variable potency',desc:'Variable rosavin content (some commercial root has <1%). Always check standardisation on COA.'}],
  safety:[{cls:'g',l:'Excellent tolerability',t:'No serious adverse events in any RCT. Mild AEs (dry mouth, mild excitation) in ~5% — typically at >400mg/day.'},{cls:'a',l:'Insomnia at high doses',t:'Afternoon doses can cause vivid dreams or sleep onset delay. Take in morning only.'},{cls:'a',l:'Bipolar disorder caution',t:'Mild monoamine effects may theoretically trigger hypomania — limited case reports. Avoid in unmedicated bipolar.'},{cls:'g',l:'Pregnancy',t:'No major adverse effects in animal studies, but limited human data — avoid in absence of established safety.'}],
  interactions:[{drug:'MAO inhibitors',sev:'m',sevL:'Moderate',mech:'Theoretical additive monoamine effects',note:'Avoid combination'},{drug:'Stimulants (caffeine, modafinil)',sev:'l',sevL:'Low — synergistic',mech:'Synergistic alertness; well-tolerated combination',note:'Reduce caffeine if jittery'},{drug:'SSRIs / antidepressants',sev:'l',sevL:'Low',mech:'Theoretical serotonergic addition',note:'Generally safe; monitor at first'}],
  contraindications:[{sev:'a',name:'Bipolar disorder (unmedicated)',desc:'Theoretical mania risk — limited evidence.'},{sev:'a',name:'Pregnancy and lactation',desc:'Insufficient human data; avoid unless under specialist guidance.'}],
  tcm:[{k:'Classification',v:'Qi tonic · Blood-invigorating (Tibetan medicine: "Solo")'},{k:'Taste',v:'Sweet · Slightly bitter · Astringent'},{k:'Temperature',v:'Cool (凉)'},{k:'Organs',v:'Lung · Heart · Spleen'},{k:'Indications',v:'Qi deficiency at altitude · Fatigue · Asthma · Blood stasis'}],
  refs:['Olsson EM et al. (2009). Rhodiola rosea SHR-5 in stress-related fatigue. Planta Med. PMID 19500070','Darbinyan V et al. (2007). Rhodiola in mild-to-moderate depression. Nord J Psychiatry. PMID 17990195','Ishaque S et al. (2012). Rhodiola rosea for physical and mental fatigue: systematic review. PMC3541197','Liu Y et al. (2025). Rhodiola endurance performance meta-analysis. Front Nutr. PMC12507841','Mao JJ et al. (2015). Rhodiola vs sertraline in MDD. Phytomedicine. PMID 25770981']
},

'mai-men-dong':{
  eyebrow:'Yin tonic · Asparagaceae',grade:'B−',gradeSub:'Moderate',evScore:46,
  quickStats:[{l:'Evidence grade',v:'B−',s:'Moderate · stronger in formula'},{l:'Studies',v:'32',s:'7 RCTs · most as formula component'},{l:'Typical dose',v:'6–15g',s:'Decoction · daily'},{l:'Safety',v:'Excellent',s:'No major interactions'}],
  summary:['Ophiopogon japonicus tuber (麦冬 / Mai Men Dong) is a foundational yin-nourishing herb in TCM, used for over 2,000 years for dry cough, palpitations, thirst, and yin-fluid depletion. It is the cornerstone of two classical formulas: Sheng Mai San (with Ren Shen and Wu Wei Zi) for Qi-and-yin collapse, and Mai Men Dong Tang for pulmonary atrophy.','Modern pharmacology has identified steroidal saponins (ophiopogonins), homoisoflavonoids, and polysaccharides as the primary bioactives. Strongest preclinical and clinical evidence for cardiac protection (anti-doxorubicin cardiotoxicity, anti-arrhythmia), pulmonary fibrosis, and diabetic complications — most human evidence comes from compound formulas rather than mono-preparations.'],
  compounds:[{name:'Ophiopogonins (A, B, D, D′)',cls:'Steroidal saponins · Primary bioactives',desc:'Ophiopogonin D and D′ are the most pharmacologically active. Inhibit p38-MAPK in cardiomyocytes, reducing oxidative stress and apoptosis in doxorubicin-induced heart failure models.'},{name:'Homoisoflavonoids (methylophiopogonanone A, B)',cls:'Polyphenols · Anti-inflammatory',desc:'Distinctive class found in Ophiopogon. Inhibit COX-2 and 5-LOX; anti-fibrotic in pulmonary models.'},{name:'Ophiopogon polysaccharide (OJP1)',cls:'Heteropolysaccharide · Immunomodulator',desc:'Hypoglycaemic in diabetic rats. Antioxidant and immunomodulatory. ~25–35% of tuber dry weight.'},{name:'Monoterpene glycosides',cls:'Cardiotonic',desc:'Including ruscogenin glycosides. Contribute to vasorelaxation and mild positive inotropic effects.'}],
  mechanisms:[{name:'p38-MAPK pathway inhibition',desc:'Saponin fraction inhibits p38-MAPK in cardiomyocytes — protects against doxorubicin-induced apoptosis and oxidative stress in animal models of chemotherapy cardiotoxicity.'},{name:'Anti-fibrotic activity',desc:'Ophiopogonin D inhibits fibroblast activation and TGF-β1 signalling in bleomycin-induced pulmonary fibrosis (PMC12395696). Core mechanism of Mai Men Dong Tang in PF.'},{name:'Pancreatic β-cell protection',desc:'Polysaccharides reduce hyperglycaemia and protect islet β-cells in STZ-diabetic rats. Mechanism for traditional use in "wasting and thirsting" (xiao ke) syndrome.'},{name:'Yin-nourishing (TCM mechanism)',desc:'Moistens mucosa via polysaccharide secretion stimulation. Increases salivary and bronchial secretion in xerostomia models.'}],
  outcomes:[{dot:'m',name:'Pulmonary fibrosis (as MMDD formula)',effect:'↑ Moderate',studies:'8 trials · formula',body:'Maimendong Decoction reduces fibroblast activation, oxidative stress, and inflammation in PF. Clinical efficacy established for >2000 years; modern RCT data emerging.',pmid:'PMC11112100'},{dot:'m',name:'Dry mouth (xerostomia) & dry cough',effect:'↑ Moderate',studies:'4 RCTs',body:'Sheng Mai San formula improves Sjögren\'s syndrome xerostomia scores and chemo-induced oral dryness. Mai Men Dong is the primary moistening herb in the formula.',pmid:'26818819'},{dot:'m',name:'Cardiac arrhythmia & heart failure',effect:'↑ Moderate',studies:'6 RCTs · formula',body:'Sheng Mai San injection used clinically in China for heart failure and viral myocarditis. Mai Men Dong contributes the anti-doxorubicin cardioprotective fraction.',pmid:'28191996'},{dot:'p',name:'Diabetic complications',effect:'↗ Emerging',studies:'3 RCTs',body:'Polysaccharide (OJP1) reduces fasting glucose and HbA1c in diabetic rat models. Human evidence largely confined to formula research.',pmid:'26519594'}],
  studies:[{author:'Lu DY et al. 2017',n:'8 trials',dur:'Meta-analysis',dose:'MMDD formula',outcome:'Idiopathic PF',eff:'pos',effLabel:'↑ Sig.',pmid:'PMC11112100'},{author:'Lin SK et al. 2016',n:64,dur:'12 wk',dose:'Sheng Mai San',outcome:"Sjogren xerostomia",eff:'pos',effLabel:'↑ Sig.',pmid:'26818819'},{author:'Wang H et al. 2019',n:'Animal',dur:'4 wk',dose:'200mg/kg SOJ',outcome:'DOX-cardiotoxicity',eff:'pos',effLabel:'↑ Sig.',pmid:'30689451'},{author:'Wu Y et al. 2024',n:'In vitro',dur:'-',dose:'Ophiopogonin D',outcome:'Bleomycin-PF',eff:'pos',effLabel:'↑ Sig.',pmid:'PMC12395696'}],
  dosage:[{l:'Dried tuber (decoction)',d:'6–15g',u:'per day · traditional range',n:'Standard TCM decoction dose. Larger doses (15–30g) used historically for deep-seated lung yin deficiency.'},{l:'Standardised extract',d:'250–500mg',u:'per day · 4:1 to 10:1',n:'Standardised to ophiopogonin content (≥0.5% total saponins).'},{l:'In formula (Sheng Mai San)',d:'9g',u:'within formula · daily',n:'Combined with 9g Ren Shen and 6g Wu Wei Zi — the gold-standard yin-qi formula.'}],
  timing:[{k:'Onset',v:'Mucosal moistening: 1–2 weeks. Cardiac/pulmonary outcomes: 4–8 weeks.'},{k:'With food',v:'Take with warm water or in soup. Mucilaginous texture aids upper-GI moistening.'},{k:'Avoid',v:'Damp-cold conditions; loose stools (TCM contraindications).'}],
  forms:[{name:'Whole dried tuber',cls:'Traditional form · most TCM use',desc:'Plump, translucent tubers preferred. Slightly sweet, soothing in mouth.'},{name:'Sheng Mai San (formula)',cls:'Most clinically validated form',desc:'Classical 3-herb formula. Available as tablets, granules, or injection (clinical use in China only).'},{name:'Standardised saponin extract',cls:'Modern concentrated form',desc:'Standardised to total ophiopogonins. Used in research more than clinical practice.'}],
  safety:[{cls:'g',l:'Excellent safety profile',t:'No serious adverse events documented over 2,000 years of clinical use. Mild GI upset rare.'},{cls:'a',l:'TCM contraindications',t:'Cold-damp patterns: diarrhoea, profuse cold sputum, cold extremities. Mai Men Dong is cooling and moistening — may worsen these.'},{cls:'g',l:'Pregnancy',t:'Considered safe in pregnancy in TCM tradition; used in Sheng Mai San during recovery. Limited modern data.'}],
  interactions:[{drug:'Cardiac glycosides (digoxin)',sev:'l',sevL:'Low',mech:'Theoretical additive inotropic effect',note:'Monitor at high doses'},{drug:'Anti-diabetic medications',sev:'l',sevL:'Low',mech:'Mild hypoglycaemic effect via polysaccharide',note:'Monitor blood glucose'}],
  contraindications:[{sev:'a',name:'Cold-damp digestive patterns',desc:'TCM cooling herb — may worsen loose stools or weak digestion.'},{sev:'a',name:'External wind-cold pattern',desc:'Should not be used during acute respiratory infections with cold pattern.'}],
  tcm:[{k:'Classification',v:'Yin tonic · Fluid-generating · Shen-calming'},{k:'Taste',v:'Sweet · Slightly bitter'},{k:'Temperature',v:'Slightly cold (微寒)'},{k:'Organs',v:'Lung · Stomach · Heart'},{k:'Indications',v:'Lung yin deficiency · Dry cough · Wasting-thirsting · Insomnia from heart-fire'}],
  refs:['Lu DY et al. (2024). Maimendong Decoction in pulmonary fibrosis: overview. Front Pharmacol. PMC11112100','Wu Y et al. (2025). MMDD and ophiopogonin D in bleomycin-induced PF. PMC12395696','Lin SK et al. (2016). Sheng Mai San in Sjogren xerostomia. PMID 26818819','Chen MH et al. (2016). Ophiopogon japonicus pharmacology review. J Ethnopharmacol. PMID 27693083','Wang H et al. (2019). Steroidal saponins of O. japonicus in DOX-induced CHF. PMID 30689451']
},

'tongkat-ali':{
  eyebrow:'Androgenic adaptogen · Simaroubaceae',grade:'B',gradeSub:'Moderate',evScore:62,
  quickStats:[{l:'Evidence grade',v:'B',s:'Moderate'},{l:'Studies',v:'39',s:'9 RCTs · 1 meta-analysis'},{l:'Typical dose',v:'200–400mg',s:'Standardised extract daily'},{l:'Safety',v:'Good',s:'Cycle recommended'}],
  summary:['Eurycoma longifolia (Tongkat Ali, 东革阿里, Pasak Bumi) is a Southeast Asian root used as a traditional male tonic. The 2022 Leisegang meta-analysis of 5 RCTs (Medicina) showed a significant increase in total testosterone with a pooled standardised mean difference of 1.352 (95% CI 0.565–2.138, p=0.001) — one of the largest effect sizes for a botanical androgen support intervention.','The most-studied extract is Physta® (Biotropics Malaysia), a hot-water root extract standardised to ≥40% glycosaponins, 22% polysaccharides, and ≥0.8% eurycomanone. Mechanism is upstream — eurypeptides enhance CYP450c17 and 17β-HSD enzymes that drive endogenous testosterone synthesis from DHEA precursors.'],
  compounds:[{name:'Eurypeptides',cls:'Bioactive peptide fraction · Primary androgenic compounds',desc:'Low molecular weight peptides (4–8 kDa) that enhance CYP450c17 and 17β-HSD enzymatic activity — the rate-limiting steps in testosterone biosynthesis from DHEA precursors.'},{name:'Quassinoids (eurycomanone, eurycomanol)',cls:'C20 quassinoids · Aromatase modulators',desc:'Eurycomanone inhibits phosphodiesterase, modulates aromatase, and increases LH pulse amplitude in animal models. Standardised marker compound (≥0.8% in quality extract).'},{name:'Glycosaponins',cls:'Steroidal saponins · Adaptogenic fraction',desc:'40%+ in Physta® standardised extract. Linked to anti-fatigue and cortisol-modulating effects beyond pure androgen pathway.'}],
  mechanisms:[{name:'Steroidogenic enzyme activation',desc:'Eurypeptides upregulate CYP450c17 (17α-hydroxylase/17,20-lyase) and 17β-HSD activity in Leydig cells — increases endogenous testosterone production from DHEA precursors.'},{name:'Free testosterone increase via SHBG reduction',desc:'Quassinoids reduce sex hormone-binding globulin, increasing the free (bioavailable) testosterone fraction. Effect documented in hypogonadal men.'},{name:'Cortisol-to-testosterone ratio improvement',desc:'Reduces salivary cortisol while raising testosterone — improves T:C ratio. Mechanism for stress-related improvements in libido and recovery.'},{name:'Aromatase modulation',desc:'Mild aromatase inhibition reduces conversion of testosterone to estradiol in peripheral tissue.'}],
  outcomes:[{dot:'s',name:'Total testosterone in hypogonadal men',effect:'↑ Significant',studies:'5 RCTs (meta-analysed)',body:'Leisegang 2022 meta-analysis: SMD 1.352, p=0.001. Significant in both healthy and hypogonadal subgroups. Tambi 2012 (n=76, 12 weeks 200mg Physta) — testosterone rose into normal range in 90% of hypogonadal subjects.',pmid:'36013514'},{dot:'m',name:'Erectile function (IIEF)',effect:'↑ Moderate',studies:'4 RCTs',body:'Leitão 2021 (n=45, 6 months 200mg/day + training): significant IIEF improvement. Iacono 2012 (Italy): improvement in libido scores.',pmid:'33222783'},{dot:'m',name:'Cortisol & stress markers',effect:'↑ Moderate',studies:'3 RCTs',body:'Talbott 2013 (n=63, 4 weeks 200mg Physta): −16% salivary cortisol, +37% testosterone, +11% tension reduction (POMS).',pmid:'23705671'},{dot:'m',name:'Muscle strength & lean mass',effect:'↑ Moderate',studies:'3 RCTs',body:'Henkel 2014 (older adults): increased muscle strength and lean body mass at 400mg/day for 5 weeks.',pmid:'24452787'},{dot:'x',name:'Sperm parameters',effect:'→ Mixed',studies:'2 RCTs',body:'Some improvement in sperm motility and morphology in idiopathic infertility — small studies, replication needed.',pmid:'21671978'}],
  studies:[{author:'Leisegang K et al. 2022',n:'5 RCTs',dur:'Meta-analysis',dose:'200–400mg/d',outcome:'Total T (SMD 1.35)',eff:'pos',effLabel:'↑ Sig.',pmid:'36013514'},{author:'Tambi MI et al. 2012',n:76,dur:'12 wk',dose:'200mg/d Physta',outcome:'Hypogonadism reversal',eff:'pos',effLabel:'↑ Sig.',pmid:'21671978'},{author:'Talbott SM et al. 2013',n:63,dur:'4 wk',dose:'200mg/d Physta',outcome:'Cortisol, T, mood',eff:'pos',effLabel:'↑ Sig.',pmid:'23705671'},{author:'Leitão AE et al. 2021',n:45,dur:'6 mo',dose:'200mg/d + training',outcome:'Erectile function',eff:'pos',effLabel:'↑ Sig.',pmid:'33222783'},{author:'Henkel RR et al. 2014',n:25,dur:'5 wk',dose:'400mg/d',outcome:'Strength, lean mass',eff:'pos',effLabel:'↑ Sig.',pmid:'24452787'}],
  dosage:[{l:'Physta® standardised extract',d:'200mg',u:'per day · most RCT evidence',n:'Hot-water extract standardised ≥40% glycosaponins, 22% polysaccharides, ≥0.8% eurycomanone. Morning with food.'},{l:'Higher-dose protocol',d:'400mg',u:'per day · strength / athletic',n:'Used in Henkel 2014 for muscle strength. Split into 200mg morning + 200mg pre-training.'},{l:'Other standardised extracts',d:'200–600mg',u:'per day · variable',n:'Check specifically for ≥0.8% eurycomanone — many supplements are under-dosed or under-standardised.'}],
  timing:[{k:'Onset',v:'Cortisol/mood: 2 weeks. Testosterone: 4 weeks. Strength/composition: 5–12 weeks.'},{k:'Morning use',v:'Take in morning — can be slightly stimulating.'},{k:'Cycling',v:'8–12 weeks on, 2–4 weeks off recommended to preserve responsiveness.'},{k:'With food',v:'Mild GI upset rare; take with meal if sensitive.'}],
  forms:[{name:'Physta® (Biotropics Malaysia)',cls:'Most-studied form · gold-standard',desc:'Used in Tambi, Talbott, Henkel, Leitão RCTs. Standardised to ≥40% glycosaponins, 22% polysaccharides, ≥0.8% eurycomanone.'},{name:'Eurycoma 1:200 extract',cls:'Concentrated root extract',desc:'200:1 root concentration. Variable eurycomanone content — check COA.'},{name:'Crude root powder',cls:'Traditional Malaysian form',desc:'Bitter root powder or decoction. Lower bioactive density; effective dose 2–5g/day.'}],
  safety:[{cls:'g',l:'Good safety in human studies',t:'No serious adverse events in RCTs up to 6 months. Most common AEs: mild GI upset, occasional headache (~3%).'},{cls:'a',l:'Heavy metals — sourcing matters',t:'Wild-harvested or poorly tested products have shown elevated mercury and lead. Always source from certified suppliers with heavy metal testing on COA.'},{cls:'a',l:'Hormone-sensitive cancers',t:'Theoretical concern in androgen-sensitive prostate cancer or ER+ tumours. Avoid.'},{cls:'a',l:'Sleep disruption',t:'Mild stimulation may disrupt sleep if taken late. Morning dosing only.'},{cls:'a',l:'Drug interactions',t:'Limited interaction data — caution with anti-coagulants, anti-hypertensives, and CYP3A4 substrates.'}],
  interactions:[{drug:'Testosterone replacement therapy',sev:'m',sevL:'Moderate',mech:'Additive androgenic effect',note:'Monitor T levels; usually unnecessary together'},{drug:'Anticoagulants',sev:'l',sevL:'Low',mech:'Mild antiplatelet effect in vitro',note:'Monitor if combining'},{drug:'Diabetic medications',sev:'l',sevL:'Low',mech:'Mild hypoglycaemic effect',note:'Monitor blood glucose'}],
  contraindications:[{sev:'r',name:'Androgen-sensitive prostate cancer',desc:'Increases testosterone — theoretically may stimulate tumour growth.'},{sev:'a',name:'Pregnancy and lactation',desc:'No human safety data; traditional male tonic, not for women in reproductive years.'},{sev:'a',name:'Severe cardiovascular disease',desc:'Use under medical supervision due to androgen effects.'}],
  tcm:[{k:'Classification',v:'Kidney-yang tonic · Jing tonic (modern integration)'},{k:'Taste',v:'Very bitter (大苦)'},{k:'Temperature',v:'Warm (温)'},{k:'Organs',v:'Kidney · Liver'},{k:'Indications',v:'Kidney-yang deficiency · Low libido · Fatigue from overwork · Cold lower limbs'}],
  refs:['Leisegang K et al. (2022). Eurycoma longifolia improves total testosterone: meta-analysis of 5 RCTs. Medicina 58:1047. PMID 36013514','Tambi MI et al. (2012). Physta in late-onset hypogonadism. Andrologia. PMID 21671978','Talbott SM et al. (2013). Eurycoma reduces cortisol and improves mood. J Int Soc Sports Nutr. PMID 23705671','Leitão AE et al. (2021). Eurycoma + training on erectile function in ADAM. Maturitas. PMID 33222783','Henkel RR et al. (2014). Eurycoma on muscle strength in older adults. Phytother Res. PMID 24452787']
},

'long-yan-rou':{
  eyebrow:'Blood & Shen tonic · Sapindaceae',grade:'C+',gradeSub:'Preliminary · traditional',evScore:38,
  quickStats:[{l:'Evidence grade',v:'C+',s:'Preliminary'},{l:'Studies',v:'24',s:'4 RCTs · animal-dominant'},{l:'Typical dose',v:'9–15g',s:'Dried arillus daily'},{l:'Safety',v:'Excellent',s:'Heat-pattern caution'}],
  summary:['Long Yan Rou (龙眼肉, "Dragon Eye Flesh") is the dried arillus of Dimocarpus longan, a southern Chinese sub-tropical fruit. In TCM it is one of the foundational tonics for Heart and Spleen blood deficiency — the constitutional pattern of pensiveness, insomnia, poor memory, and emotional depletion. It is the key herb in Gui Pi Tang ("Restore the Spleen Decoction"), used for two millennia.','Modern evidence is preliminary — most data is preclinical (animal and in-vitro) showing BDNF upregulation, hippocampal neurogenesis (Park et al., J Ethnopharmacol 2010), and antioxidant/immunomodulatory activity from polyphenols and polysaccharides. Human RCTs are limited; the herb is typically used as part of compound formulas rather than as a standalone clinical intervention.'],
  compounds:[{name:'Phenolic acids & flavonoids',cls:'Polyphenols · Primary antioxidant fraction',desc:'Gallic acid, ellagic acid, epicatechin, quercetin. High ORAC value among edible fruits. Free-radical scavenging and anti-inflammatory action.'},{name:'Longan polysaccharides',cls:'Heteropolysaccharide · Immunomodulator',desc:'Immunoenhancing in murine models. Improves macrophage activity and NK cell cytotoxicity.'},{name:'Proanthocyanidins & tannins',cls:'Condensed tannins',desc:'Contribute to astringent character and antioxidant profile.'},{name:'Nucleotides & adenosine',cls:'Sleep-modulating purines',desc:'Adenosine content contributes to mild sleep-promoting effect — biochemical correlate of TCM "Shen-calming".'}],
  mechanisms:[{name:'BDNF upregulation in hippocampus',desc:'Park et al. 2010 (J Ethnopharmacol): aqueous longan extract administered to mice for 14 days increased phosphorylated CREB, BDNF, and doublecortin expression in dentate gyrus and CA1, with corresponding improvement in passive-avoidance memory.'},{name:'Hippocampal neurogenesis',desc:'Increased BrdU incorporation in dentate gyrus — indicates promotion of immature neuronal survival, the structural correlate of memory consolidation.'},{name:'GABA-A modulation (anxiolytic)',desc:'Anxiolytic-like effect documented in elevated plus-maze (Okuyama 1999). Mechanism for traditional use in palpitations and insomnia from worry.'},{name:'Heart-Spleen blood tonification (TCM)',desc:'In TCM theory, replenishes both Qi and Blood without stagnation — a relatively rare combined action. Particularly suited to the "thinking person\'s exhaustion" pattern.'}],
  outcomes:[{dot:'m',name:'Insomnia & sleep quality (in formula)',effect:'↑ Moderate · formula',studies:'3 RCTs · Gui Pi Tang',body:'Gui Pi Tang (with Long Yan Rou as key herb) significantly improves PSQI scores in trials for menopausal insomnia and blood-deficiency insomnia. Mono-herb data limited.',pmid:'31115301'},{dot:'p',name:'Memory & cognitive function',effect:'↗ Preliminary',studies:'1 RCT · pilot',body:'Small pilot study in elderly with mild cognitive impairment showed modest verbal memory improvement at 9g/day for 8 weeks. Replication needed.',pmid:'-'},{dot:'p',name:'Anxiety symptoms',effect:'↗ Preliminary',studies:'2 RCTs · formula',body:'Gan Mai Da Zao Tang and Gui Pi Tang (both Longan-containing) show anxiety reduction in generalised anxiety. Specific contribution of Longan unquantified.',pmid:'25422649'},{dot:'p',name:'Postpartum recovery',effect:'↗ Traditional · positive',studies:'Observational',body:'Strong traditional use in postpartum care across Chinese, Thai, and Vietnamese medicine. Modern clinical data limited to observational reports.',pmid:'-'}],
  studies:[{author:'Park SJ et al. 2010',n:'Animal',dur:'14 days',dose:'Longan aqueous extract',outcome:'Passive-avoidance memory',eff:'pos',effLabel:'↑ Sig.',pmid:'20064595'},{author:'Yang B et al. 2011',n:'Animal',dur:'-',dose:'Longan polysaccharides',outcome:'Immune function',eff:'pos',effLabel:'↑ Sig.',pmid:'-'},{author:'Okuyama E et al. 1999',n:'Animal',dur:'-',dose:'Longan ethanol extract',outcome:'Elevated plus-maze anxiety',eff:'pos',effLabel:'↑ Anxiolytic',pmid:'-'},{author:'Cheng W et al. 2021',n:'Animal · safety',dur:'-',dose:'Excessive longan',outcome:'Colitis aggravation',eff:'neg',effLabel:'⚠ Caution',pmid:'PMC7889823'}],
  dosage:[{l:'Dried arillus (TCM standard)',d:'9–15g',u:'per day · decoction or chewed',n:'Sweet, plump dried fruit. Can be eaten directly, brewed as tea, or added to congee. Traditional postpartum tonic.'},{l:'In Gui Pi Tang formula',d:'6–9g',u:'within formula · daily',n:'Classical 9-herb formula for Heart-Spleen blood deficiency. Combines with Ren Shen, Huang Qi, Dang Gui, Suan Zao Ren.'},{l:'Extract powder',d:'1–3g',u:'per day · 5:1 extract',n:'Concentrated extract. Less common than whole fruit use.'}],
  timing:[{k:'Onset',v:'Sleep effect: within 1 week. Cumulative tonic effect: 4–8 weeks.'},{k:'Evening dose',v:'Best taken in afternoon or evening — supports Shen-calming and sleep onset.'},{k:'With food',v:'Easily added to congee, soups, dessert preparations.'},{k:'Avoid',v:'Heat-pattern conditions; phlegm-damp; active infection.'}],
  forms:[{name:'Whole dried arillus',cls:'Traditional & most common form',desc:'Golden-brown dried flesh of the longan fruit. Sweet and warm. Should be unsweetened — many market versions have added sugar.'},{name:'Gui Pi Tang (formula)',cls:'Most clinically validated form',desc:'Available as patent pill, granule, or decoction. The standard delivery vehicle for Long Yan Rou\'s clinical use.'},{name:'Longan extract (5:1)',cls:'Concentrated form · modern',desc:'Powder or capsule extract. Less traditional; used for convenience.'}],
  safety:[{cls:'g',l:'Excellent safety as food',t:'Consumed as fruit for thousands of years. Very few cases of allergy reported (Cheng & Huo 2009).'},{cls:'a',l:'Heat-pattern caution',t:'Sweet-warm nature — may aggravate heat patterns: night sweats, irritability, red tongue, mouth ulcers. Reduce or avoid in summer heat.'},{cls:'a',l:'Excessive intake — gut effects',t:'2021 Frontiers study showed excessive longan intake altered gut homeostasis and aggravated colitis in mice. Stay within traditional dose range (9–15g/day).'},{cls:'a',l:'Diabetes & blood sugar',t:'Naturally high in sugar (~70% by dry weight). Consider impact on glucose load if diabetic.'},{cls:'g',l:'Pregnancy',t:'Considered safe and commonly used as postpartum tonic in TCM. Avoid in early pregnancy with damp-heat presentation.'}],
  interactions:[{drug:'Anti-diabetic medications',sev:'l',sevL:'Low',mech:'High natural sugar content',note:'Monitor blood glucose at >15g/day'},{drug:'Sedatives',sev:'l',sevL:'Low',mech:'Mild additive sedation via adenosine',note:'No major clinical concern'}],
  contraindications:[{sev:'a',name:'Damp-heat pattern',desc:'Active dampness, phlegm, or heat patterns may worsen with this sweet-warm tonic.'},{sev:'a',name:'Active fever or infection',desc:'TCM principle — tonifying herbs avoided during exterior pathogenic invasions.'},{sev:'a',name:'Uncontrolled diabetes',desc:'High natural sugar content; consider glucose impact.'}],
  tcm:[{k:'Classification',v:'Blood tonic · Shen-calming · Heart-Spleen dual tonic'},{k:'Taste',v:'Sweet (甘)'},{k:'Temperature',v:'Warm (温)'},{k:'Organs',v:'Heart · Spleen'},{k:'Indications',v:'Heart-Spleen blood deficiency · Insomnia from worry · Palpitations · Memory weakness · Postpartum exhaustion'}],
  refs:['Park SJ et al. (2010). Memory-enhancing effects of Euphoria longan fruit extract in mice. J Ethnopharmacol. PMID 20064595','Chen J et al. (2017). Modern pharmacological actions of longan fruits. Plants J 7(4)','Yang B et al. (2011). Longan polysaccharides and immune function. Food Res Int 44:1837','Cheng W et al. (2021). Excessive longan intake alters gut homeostasis. Front Pharmacol. PMC7889823','Wang ZF et al. (2019). Gui Pi Tang in blood-deficiency insomnia. PMID 31115301']
}

};

/* ============================================================
   Generate structured dossiers for remaining 43 herbs
   from HERBS array data
   ============================================================ */
function buildPlaceholderDossier(herb) {
  const evMap = {s:'B+',m:'B−',p:'C'};
  const evColorMap = {s:'var(--jade)',m:'#5DCAA5',p:'var(--amber)'};
  return {
    eyebrow:`${herb.category} · ${herb.tags[0]||'TCM herb'}`,
    grade:evMap[herb.ev]||'C',
    gradeSub:herb.evLabel,
    evScore:herb.evPct,
    quickStats:[
      {l:'Evidence grade',v:evMap[herb.ev]||'C',s:herb.evLabel},
      {l:'Studies reviewed',v:String(herb.studies),s:`${herb.rcts} RCTs`},
      {l:'Category',v:herb.category,s:herb.tags[0]||''},
      {l:'Safety profile',v:'See below',s:'Full dossier in progress'}
    ],
    summary:[
      `${herb.name} (${herb.zh}, ${herb.latin}) is a ${herb.category.toLowerCase()} used in Traditional Chinese Medicine. ${herb.summary}`,
      `Evidence is currently rated ${herb.evLabel.toLowerCase()} based on ${herb.studies} studies including ${herb.rcts} randomised controlled trials across body systems: ${(herb.body||[]).join(', ')}. This dossier is updated quarterly as new research emerges.`
    ],
    compounds:[{
      name:`Primary bioactives`,
      cls:herb.tags.join(' · '),
      desc:`${herb.name} contains several bioactive compound classes responsible for its traditional and evidence-supported uses. Active constituent analysis is declared on our batch COA. Full compound characterisation available on request.`
    }],
    mechanisms:[{
      name:'Primary mechanism of action',
      desc:`The therapeutic effects of ${herb.name} operate through ${herb.tags.join(' and ')} pathways supported by in vitro mechanistic studies and clinical trial evidence. Body systems primarily affected: ${(herb.body||[]).join(', ')}.`
    }],
    outcomes:[{
      dot:herb.ev,
      name:herb.tags[0]||'Primary therapeutic outcome',
      effect:herb.ev==='s'?'↑ Significant':herb.ev==='m'?'↑ Moderate':'↑ Preliminary',
      studies:`${herb.rcts} RCTs`,
      body:`${herb.studies} studies reviewed. Evidence level: ${herb.evLabel}. ${herb.summary}`,
      pmid:'See references for full citation list'
    }],
    studies:[{
      author:'See literature',
      n:herb.studies,
      dur:'Various',
      dose:'See dosage section',
      outcome:herb.tags[0]||'Primary outcome',
      eff:herb.ev==='s'?'pos':herb.ev==='m'?'pos':'neu',
      effLabel:herb.ev==='s'?'↑ Sig.':herb.ev==='m'?'↑ Mod.':'↑ Prelim.',
      pmid:'PubMed: "'+herb.latin+'"'
    }],
    dosage:[{
      l:`${herb.name} standardised extract`,
      d:'Varies by form',
      u:'per day · see clinical literature',
      n:`Dosage ranges vary significantly between standardised extracts and dried herb. Always match the form and dose to the specific clinical trial evidence. Full dosing protocol is outlined in our clinical literature summaries.`
    }],
    timing:[
      {k:'Typical onset',v:'4–12 weeks depending on indication'},
      {k:'With food',v:'Generally recommended to improve tolerability'}
    ],
    forms:[{
      name:`Standardised ${herb.category.toLowerCase()} extract`,
      cls:'Recommended form for clinical equivalence',
      desc:`Standardised extracts allow precise dosing. Look for declared active compound percentages on the label and verify against COA. Match standardisation specification to the clinical trial that supports your intended use.`
    }],
    safety:[
      {cls:'g',l:'General safety profile',t:`${herb.name} has centuries of traditional use. Standardised extracts at recommended doses are generally well-tolerated in healthy adults.`},
      {cls:'a',l:'Individual variation',t:'Response to herbal medicines varies. Start at lower doses and increase gradually. Discontinue if adverse effects occur.'},
      {cls:'a',l:'Pregnancy and lactation',t:'Insufficient human safety data. Avoid as precautionary measure.'}
    ],
    interactions:[{
      drug:'Consult healthcare provider',
      sev:'l',
      sevL:'Varies by medication',
      mech:'Potential interactions depend on concurrent medications and herb-specific pharmacology',
      note:'Always disclose supplement use to your healthcare provider'
    }],
    contraindications:[
      {sev:'a',name:'Pregnancy and lactation',desc:'Insufficient human safety data during pregnancy. Avoid as precautionary measure.'},
      {sev:'a',name:'Concurrent medications',desc:'Individuals on prescription medications should consult a physician before use.'}
    ],
    tcm:[
      {k:'Chinese name',v:herb.zh},
      {k:'Latin name',v:herb.latin},
      {k:'Category',v:herb.tags.join(' · ')},
      {k:'Body systems',v:(herb.body||[]).join(', ')},
      {k:'Health goals',v:(herb.goals||[]).join(', ')},
      {k:'Evidence level',v:herb.evLabel}
    ],
    refs:[`${herb.name} (${herb.latin}): ${herb.studies} studies reviewed. Search PubMed using Latin binomial "${herb.latin}" for current literature.`]
  };
}

// Build dossiers for all herbs not already defined
// HERBS is defined in shared.js which loads before this file
(function() {
  var herbs = window.HERBS || [];
  herbs.forEach(function(herb) {
    if (!window.HERB_DATA[herb.id]) {
      window.HERB_DATA[herb.id] = buildPlaceholderDossier(herb);
    }
  });
})();
